# Config file for air: https://github.com/cosmtrek/air
root = "."
tmp_dir = "tmp"

[build]
  # Correctly point to your api's main.go file
  cmd = "go build -gcflags=\"all=-N -l\" -o ./tmp/main ./cmd/api/main.go"
  # Run the compiled binary with Delve for debugging
  bin = "dlv exec ./tmp/main --listen=:2345 --headless=true --api-version=2 --accept-multiclient"
  full_bin = "dlv exec ./tmp/main --listen=:2345 --headless=true --api-version=2 --accept-multiclient"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 1000 # In milliseconds

[log]
  time = true